// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7FMhHBjOmNnoqkZ4fxlYrUE6e51CeS08',
    appId: '1:1097415463252:web:3347d69e74fc9febb7f8c1',
    messagingSenderId: '1097415463252',
    projectId: 'ttfc-app-73248',
    authDomain: 'ttfc-app-73248.firebaseapp.com',
    storageBucket: 'ttfc-app-73248.appspot.com',
    measurementId: 'G-K2X54FHWE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQEZwvF28rmX0ZDOJypHSs5iWsHFcsL8',
    appId: '1:1097415463252:android:826c11523d93040eb7f8c1',
    messagingSenderId: '1097415463252',
    projectId: 'ttfc-app-73248',
    storageBucket: 'ttfc-app-73248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQjleCGs3tdL_4oV1EtO-peIyXORqJ1o',
    appId: '1:1097415463252:ios:ef90e88449fa93d0b7f8c1',
    messagingSenderId: '1097415463252',
    projectId: 'ttfc-app-73248',
    storageBucket: 'ttfc-app-73248.appspot.com',
    iosBundleId: 'com.example.ttfcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQjleCGs3tdL_4oV1EtO-peIyXORqJ1o',
    appId: '1:1097415463252:ios:ef90e88449fa93d0b7f8c1',
    messagingSenderId: '1097415463252',
    projectId: 'ttfc-app-73248',
    storageBucket: 'ttfc-app-73248.appspot.com',
    iosBundleId: 'com.example.ttfcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7FMhHBjOmNnoqkZ4fxlYrUE6e51CeS08',
    appId: '1:1097415463252:web:8e0ab366d9998418b7f8c1',
    messagingSenderId: '1097415463252',
    projectId: 'ttfc-app-73248',
    authDomain: 'ttfc-app-73248.firebaseapp.com',
    storageBucket: 'ttfc-app-73248.appspot.com',
    measurementId: 'G-CGFQ93LJTB',
  );
}
